version: "3"

services:
  mqtt-client:
    build:
      context: ./../mqtt-client
      dockerfile: ./../mqtt-client/.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - HIVEMQ_USERNAME=papaya
      - HIVEMQ_PASSWORD=something
      - HIVEMQ_BROKER_URL=ecfd1263e29f4248b00d94e4735d8ffb.s2.eu.hivemq.cloud
      - HIVEMQ_BROKER_PORT=8883
      - MQTT_CLIENTID=mqtt-publisher
      - MQTT_TELEMETRY_TOPIC=topic/test
      - MQTT_ACK_TOPIC=topic/ack

  mqtt-server:
    build:
      context: ./../mqtt-server
      dockerfile: ./../mqtt-server/.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - HIVEMQ_USERNAME=papaya
      - HIVEMQ_PASSWORD=something
      - HIVEMQ_BROKER_URL=ecfd1263e29f4248b00d94e4735d8ffb.s2.eu.hivemq.cloud
      - HIVEMQ_BROKER_PORT=8883
      - MQTT_CLIENTID=mqtt-subscriber
      - MQTT_TELEMETRY_TOPIC=topic/test
      - MQTT_ACK_TOPIC=topic/ack
  
  storage-server:
    build:
      context: ./../storage-server
      dockerfile: ./../storage-server/.dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - PARTITION="0"
